name: habits
description: A habits flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:  
      sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  adaptive_theme: ^2.3.0
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets: 
      - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/mulish/Mulish-Black.ttf
        - asset: fonts/mulish/Mulish-BlackItalic.ttf
        - asset: fonts/mulish/Mulish-Bold.ttf
        - asset: fonts/mulish/Mulish-BoldItalic.ttf
        - asset: fonts/mulish/Mulish-ExtraBold.ttf
        - asset: fonts/mulish/Mulish-ExtraBoldItalic.ttf
        - asset: fonts/mulish/Mulish-ExtraLight.ttf
        - asset: fonts/mulish/Mulish-ExtraLightItalic.ttf
        - asset: fonts/mulish/Mulish-Italic.ttf
        - asset: fonts/mulish/Mulish-Light.ttf
        - asset: fonts/mulish/Mulish-LightItalic.ttf
        - asset: fonts/mulish/Mulish-Medium.ttf
        - asset: fonts/mulish/Mulish-MediumItalic.ttf
        - asset: fonts/mulish/Mulish-Regular.ttf
        - asset: fonts/mulish/Mulish-SemiBold.ttf
        - asset: fonts/mulish/Mulish-SemiBoldItalic.ttf
          style: italic


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
