name: habits
description: A habits flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  fl_chart: ^0.50.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.0.3
  focused_menu: ^1.0.5
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  quiver: ^3.0.1+1
  int_range: ^1.0.1
  rxdart: ^0.27.3
  sqflite: ^2.0.2
  dropdown_button2: ^1.2.2
 

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/mulish/Mulish-Black.ttf
        - asset: fonts/mulish/Mulish-BlackItalic.ttf
        - asset: fonts/mulish/Mulish-Bold.ttf
        - asset: fonts/mulish/Mulish-BoldItalic.ttf
        - asset: fonts/mulish/Mulish-ExtraBold.ttf
        - asset: fonts/mulish/Mulish-ExtraBoldItalic.ttf
        - asset: fonts/mulish/Mulish-ExtraLight.ttf
        - asset: fonts/mulish/Mulish-ExtraLightItalic.ttf
        - asset: fonts/mulish/Mulish-Italic.ttf
        - asset: fonts/mulish/Mulish-Light.ttf
        - asset: fonts/mulish/Mulish-LightItalic.ttf
        - asset: fonts/mulish/Mulish-Medium.ttf
        - asset: fonts/mulish/Mulish-MediumItalic.ttf
        - asset: fonts/mulish/Mulish-Regular.ttf
        - asset: fonts/mulish/Mulish-SemiBold.ttf
        - asset: fonts/mulish/Mulish-SemiBoldItalic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
